#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-

def bake_slapd(opsys, conf, conf_dir, plugins_dir, agconf):
    target_dir = plugins_dir

    # Deploy the agent plugin
    shutil.copy2(cmk.utils.paths.local_agents_dir + "/plugins/slapd.pl", target_dir + "/slapd.pl")

    # Create the agent configuration
    content = agent_file_header
    cfg_file = conf_dir + "/slapd.cfg"

    content += "%slapd_instances = (\n"

    for instance, instconf in conf:
        content += "  '%s' => {\n" % instance
        for key, value in instconf.items():
            if key == 'syncrepl':
                content += "    'syncrepl' => [\n"
                for syncreplconf in value:
                    content += "      {\n"
                    for key, value in syncreplconf.items():
                        content += "      '%s' => '%s'\n" % (key, value)
                    content += "      },\n"
                content += "    ],\n"
            else:
                content += "    '%s' => '%s',\n" % (key, value)
        content += "  },\n"

    content += ");\n"

    file(cfg_file, "w").write(content)


bakery_info["slapd"] = {
    "bake_function": bake_slapd,
    "os": ["linux"],
}
